CREATE TABLE IF NOT EXISTS verifications_email (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    code VARCHAR(6) NOT NULL,
    type ENUM('RESERVATION','COMMANDE','AVIS') NOT NULL,
    verifie BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    verifie_le DATETIME NULL
);

ALTER TABLE reservations
    MODIFY COLUMN user_id INT NULL,
    ADD COLUMN IF NOT EXISTS guest_nom VARCHAR(100) NULL AFTER user_id,
    ADD COLUMN IF NOT EXISTS guest_email VARCHAR(150) NULL AFTER guest_nom,
    ADD COLUMN IF NOT EXISTS guest_telephone VARCHAR(30) NULL AFTER guest_email;

ALTER TABLE commandes
    MODIFY COLUMN user_id INT NULL,
    ADD COLUMN IF NOT EXISTS guest_nom VARCHAR(100) NULL AFTER user_id,
    ADD COLUMN IF NOT EXISTS guest_email VARCHAR(150) NULL AFTER guest_nom,
    ADD COLUMN IF NOT EXISTS guest_telephone VARCHAR(30) NULL AFTER guest_email;

ALTER TABLE avis
    MODIFY COLUMN user_id INT NULL,
    ADD COLUMN IF NOT EXISTS guest_nom VARCHAR(100) NULL AFTER user_id,
    ADD COLUMN IF NOT EXISTS guest_email VARCHAR(150) NULL AFTER guest_nom;