ALTER TABLE commandes
    ADD COLUMN IF NOT EXISTS saisie_par_user_id INT NULL AFTER user_id,
    MODIFY COLUMN mode_paiement ENUM('STRIPE','AIRTEL_MONEY','ORANGE_MONEY','MPESA','CONTACT_RESTAURANT','ESPECES') NULL;