CREATE TABLE IF NOT EXISTS password_resets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    token VARCHAR(64) NOT NULL,
    utilise BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expire_le DATETIME NOT NULL
);

ALTER TABLE verifications_email
    MODIFY COLUMN type ENUM('RESERVATION','COMMANDE','AVIS','EMPLOYE') NOT NULL;